#!/usr/bin/env bash
# This script displays information about subdomains for a given domain.

print_info () {
    subdomain="$1"
    domain="$2"
    record_type="$3"

    if [ -z "$record_type" ]; then
        echo "Error: Please provide a valid record type (e.g., A, CNAME) as the third argument."
        exit 1
    fi

    dig "$subdomain" "$record_type" | grep -A1 'ANSWER SECTION:' | sed -r "s/$subdomain\.$domain./$subdomain/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 3 ]; then
    print_info "$2.$1" "$2" "$3"
else
    print_info "www.$1" "www" "A"
    print_info "lb-01.$1" "lb-01" "A"
    print_info "web-01.$1" "web-01" "A"
    print_info "web-02.$1" "web-02" "A"
fi
