#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
#  return a page "Hello World"

sudo apt-get -y update
sudo apt-get install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
