#!/usr/bin/env bash
# installs nginx and configure it to listen on port 80
#  return a page "Hello World"

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo nginx -t
sudo service nginx start
sudo service nginx reload
