#!/usr/bin/env bash                                                                                                                                    
# This script configures and fix nginx listening on port 80                                                          
# Go to sites-enabled folder for Nginx                                                                                                                    
cd /etc/nginx/sites-enabled/ || exit;                                                                                                                             
# Delete default file                                                                                                                               
rm default;                                                                                                                                               
# Create symbolic-link to deafult file in sites-available                                                                                             
ln -s /etc/nginx/sites-available/default default;                                                                                                         
# Restart Nginx                                                                                                                                           
service nginx restart 
